terraform:
  backend:
    bucket_name: terraform-state-101120255555
    region: eu-central-1

docker:
  dockerhub_image: qaysalnajjad/ecs-wordpress-app:v3.6
  ecr_repo_name: ecs-wordpress-app

media:
  s3:
    primary_bucket: wordpress-media-primary-2004
    dr_bucket: wordpress-media-dr-2004

rds:
  identifier: wordpress-rds

dns:
  hosted_zone_id: Z0201471MCIEQVEUEMQF
  primary_domain: rqays.com
  certificate_sans:
    - "*.rqays.com"

certificates:
  alb:
    primary: arn:aws:acm:us-east-2:174512274809:certificate/80cf0123-dc9b-44ab-90d4-6c1f6bb1d951
    dr: ""
  cloudfront: arn:aws:acm:us-east-1:174512274809:certificate/bfdb54d1-e12c-483e-9c4a-e5697af6c65d
